# Accounting Anomaly Analytics
#
# This notebook analyzes accounting anomalies using the based on the outputs in the analytics.accounting_anomaly_analysis and public.quality_risk table :
# - **Accounting Anomaly Analysis** — Probability-weighted accounting anomaly signals
# - **Quality Risk Analysis** — Probability-weighted quality risk signals
# - **Cross-Model Comparison** — Accounting anomaly vs Quality risk model alignment
#
# Data sources: `analytics.accounting_anomaly_analysis`, `public.vw_features_quality_risk`

In [1]:
%%sql
SELECT * FROM analytics.accounting_anomaly_analysis;

,isin,ticker,name,region,country,trading_country,exchange,sector,industry,dividend_record_frequency,...,goodwill_change_rate_dist_pvalue,mahalanobis_distance,sector_relative_anomaly,benford_chi2_pvalue,anomaly_feature_count,accounting_anomaly_tier,anomaly_severity_score,anomaly_risk_rank,sector_anomaly_percentile,multi_flag_alert
0,CNE0000010Y1,000951,Sinotruk Jinan Truck Co.Ltd,Asia / Pacific,CN,CN,SZSE,Industrials,Machinery,Interim Payment,...,0.0,NaN,0.477676,0.007675,1,Flag,39.172798,78.294574,79.452055,False
1,CNE100005RH3,688234,SICC Co. Ltd.,Asia / Pacific,CN,CN,SHSE,Information Technology,Semiconductors and Semiconductor Equipment,NaN,...,0.0,NaN,1.353862,0.007675,1,Flag,39.130838,78.076550,87.980769,False
2,CNE100000510,1385,Shanghai Fudan Microelectronics Group Company ...,Asia / Pacific,CN,HK,SEHK,Information Technology,Semiconductors and Semiconductor Equipment,Annual,...,0.0,NaN,-0.938798,0.007675,0,Clean,5.935438,16.509205,24.519231,False
3,CNE1000062T0,688025,Shenzhen JPT Opto-Electronics Co. Ltd.,Asia / Pacific,CN,CN,SHSE,Information Technology,Electronic Equipment Instruments and Components,Annual,...,0.0,NaN,1.267296,0.007675,2,Flag,43.623430,88.032946,87.500000,False
4,CNE000001CP8,600499,Keda Industrial Group Co. Ltd.,Asia / Pacific,CN,CN,SHSE,Industrials,Machinery,Annual,...,0.0,NaN,-0.785012,0.007675,2,Watch,24.367736,53.197674,36.073059,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4123,CNE000000J93,600879,China Aerospace Times Electronics CO. LTD.,Asia / Pacific,CN,CN,SHSE,Industrials,Aerospace and Defense,Annual,...,0.0,NaN,0.738814,0.007675,0,Watch,30.890750,62.209302,76.543210,False
4124,CNE1000059B4,688279,Fortior Technology (Shenzhen) Co. Ltd.,Asia / Pacific,CN,CN,SHSE,Information Technology,Semiconductors and Semiconductor Equipment,Annual,...,0.0,NaN,1.312115,0.007675,0,Flag,35.253751,69.743217,84.134615,False
4125,CNE000001F88,600435,North Navigation Control Technology Co.Ltd.,Asia / Pacific,CN,CN,SHSE,Industrials,Machinery,Annual,...,0.0,NaN,-1.121049,0.007675,0,Clean,12.873930,29.142442,26.940639,False
4126,CNE100002FZ7,603228,Shenzhen Kinwong Electronic Co. Ltd.,Asia / Pacific,CN,CN,SHSE,Information Technology,Electronic Equipment Instruments and Components,Annual,...,0.0,NaN,-0.224168,0.007675,0,Clean,16.748289,35.150194,36.904762,False
4127,CNE100001V94,603997,Ningbo Jifeng Auto Parts Co. Ltd.,Asia / Pacific,CN,CN,SHSE,Consumer Discretionary,Automobile Components,NaN,...,0.0,NaN,-0.096323,0.007675,1,Watch,22.931813,48.473837,44.791667,False

In [2]:
%%sql
SELECT * FROM public.vw_features_quality_risk;

,isin,ticker,name,region,country,trading_country,exchange,sector,industry,dividend_record_frequency,...,asset_writedown_ltm,restructuring_ltm,has_goodwill_impairment_ltm,goodwill_impairment_frequency,asset_writedown_frequency,restructuring_frequency,exceptional_items_total_ltm,exceptional_items_to_ebitda_comp,quality_issues_count_5y,accounting_quality_score_comp
0,US0231351067,AMZN,Amazon.com Inc.,United States and Canada,US,US,NasdaqGS,Consumer Discretionary,Broadline Retail,NaN,...,0.00,0.0,0,0,1,0,0.00,0.000000,1,96
1,NO0003033102,KOA,Kongsberg Automotive ASA,Europe,NO,NO,OB,Consumer Discretionary,Automobile Components,NaN,...,-3.17,0.0,0,0,4,0,3.17,0.058154,4,84
2,US30303M1027,META,Meta Platforms Inc.,United States and Canada,US,US,NasdaqGS,Communication Services,Interactive Media and Services,Quarterly,...,0.00,0.0,0,0,0,3,0.00,0.000000,3,88
3,US02079K3059,GOOGL,Alphabet Inc.,United States and Canada,US,US,NasdaqGS,Communication Services,Interactive Media and Services,Quarterly,...,0.00,0.0,0,0,0,1,0.00,0.000000,1,96
4,CA36256R1055,GTWO,G2 Goldfields Inc.,United States and Canada,CA,CA,TSX,Materials,Metals and Mining,NaN,...,0.00,0.0,0,0,0,0,0.00,0.000000,0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6389,CA0089118776,AC,Air Canada,United States and Canada,CA,CA,TSX,Industrials,Passenger Airlines,NaN,...,0.00,0.0,0,0,2,1,0.00,0.000000,3,88
6390,US25809K1051,DASH,DoorDash Inc.,United States and Canada,US,US,NasdaqGS,Consumer Discretionary,Hotels Restaurants and Leisure,NaN,...,-11.00,-2.0,0,0,4,3,13.00,0.010673,7,72
6391,GB00BLGYDT21,MTEC,Made Tech Group Plc,Europe,GB,GB,AIM,Information Technology,IT Services,NaN,...,0.00,0.0,0,0,1,2,0.00,0.000000,3,88
6392,GB00BMBWCV32,AMCO,Amcomri Group plc,Europe,GB,GB,AIM,Industrials,Professional Services,NaN,...,0.00,0.0,0,0,0,0,0.00,0.000000,0,100
6393,US92343V1044,VZ,Verizon Communications Inc.,United States and Canada,US,US,NYSE,Communication Services,Diversified Telecommunication Services,Quarterly,...,0.00,-2389.0,0,1,0,5,2389.00,0.047783,6,72