In [1]:
%%sql
# SELECT * FROM monte_carlo_simulation

,ticker,name,country,exchange,sector,industry,expected_upside,upside_std,var_5_pct,prob_positive,risk_reward_ratio,last_price,pt_median
0,DSSA,PT Dian Swastatika Sentosa Tbk,ID,IDX,Energy,Oil Gas and Consumable Fuels,75.695465,0.000003,75.695462,100.0,2.017667e+07,85375.0,150000.0000
1,PTRO,PT Petrosea Tbk,ID,IDX,Materials,Metals and Mining,179.476040,0.000041,179.475987,100.0,4.264885e+06,5725.0,16000.0000
2,MRSHL,Marshall Boya Ve Vernik Sanayii A.S.,TR,IBSE,Materials,Chemicals,613.267176,0.000152,613.266980,100.0,4.020359e+06,1565.0,11162.6280
3,SNTS,Sonatel SA,SN,BRVM,Communication Services,Diversified Telecommunication Services,38.107420,0.000009,38.107408,100.0,3.924074e+06,27000.0,37289.0000
4,AMMN,PT Amman Mineral Internasional Tbk,ID,IDX,Materials,Metals and Mining,30.429839,0.000032,30.429796,100.0,9.156868e+05,7250.0,9456.1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4698,ANY,ANY Biztonsági Nyomda Nyrt.,HU,BUSE,Industrials,Commercial Services and Supplies,-13.337586,0.000030,-13.337625,0.0,-9.999971e-01,7760.0,6725.0000
4699,SRAJ,PT Sejahteraraya Anugrahjaya Tbk,ID,IDX,Health Care,Health Care Providers and Services,-17.812479,0.000015,-17.812498,0.0,-9.999990e-01,16000.0,13150.0000
4700,6330,Toyo Engineering Corporation,JP,TSE,Industrials,Construction and Engineering,-87.883163,0.000034,-87.883208,0.0,-9.999995e-01,6850.0,830.0000
4701,A017800,Hyundai Elevator Co. Ltd,KR,KOSE,Industrials,Machinery,-5.088059,0.000002,-5.088062,0.0,-9.999996e-01,102200.0,97000.0000
4702,BSR,Binh Son Refining and Petrochemical Joint Stoc...,VN,HOSE,Energy,Oil Gas and Consumable Fuels,-39.467680,0.000010,-39.467693,0.0,-9.999997e-01,24550.0,14860.6811

In [2]:
%%sql
# SELECT * FROM price_target_achievement

,ticker,name,country,exchange,sector,industry,achievement_probability,upside_potential,price_target_spread_pct,analyst_conviction,eps_revision_momentum,analyst_rating_normalized,expected_return_prob_weighted,confidence_level
0,AER,AerCap Holdings N.V.,IE,NYSE,Industrials,Trading Companies and Distributors,0.83,12.086814,13.375796,88.888889,0.038825,89.00,10.032055,High
1,PM,Philip Morris International Inc.,US,NYSE,Consumer Staples,Tobacco,0.90,-1.537115,23.333333,63.157895,0.006085,77.75,-1.383404,Medium
2,UAA,Under Armour Inc.,US,NYSE,Consumer Discretionary,Textiles Apparel and Luxury Goods,0.85,-27.248677,174.545455,12.000000,0.128545,57.00,-23.161376,Low
3,GGD,GoGold Resources Inc.,CA,TSX,Materials,Metals and Mining,0.54,59.235669,0.000000,100.000000,0.604565,100.00,31.987261,Low
4,NVT,nVent Electric plc,GB,NYSE,Industrials,Electrical Equipment,0.62,15.411932,59.200000,92.857143,0.039150,92.75,9.555398,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6414,INRN,Interroll Holding AG,CH,SWX,Industrials,Machinery,0.39,33.333333,26.576923,57.142857,0.006545,75.00,13.000000,Medium
6415,LOTB,Lotus Bakeries NV,BE,ENXTBR,Consumer Staples,Food Products,0.90,-6.250000,35.353535,60.000000,0.015580,82.50,-5.625000,Low
6416,YSN,secunet Security Networks Aktiengesellschaft,DE,XTRA,Information Technology,IT Services,0.65,25.183374,21.484375,75.000000,0.091300,87.50,16.369193,Medium
6417,KOMN,Komax Holding AG,CH,SWX,Industrials,Machinery,0.84,-2.139800,32.069971,0.000000,0.000000,55.00,-1.797432,Medium
6418,ALLAN,Lanson-BCC,FR,ENXTPA,Consumer Staples,Beverages,0.25,32.996633,27.848101,50.000000,-0.066880,75.00,8.249158,Medium

In [3]:
%%sql
# SELECT * FROM kalman_filtered_price_targets

,ticker,name,country,exchange,sector,industry,kalman_estimate,kalman_variance,kalman_gain,signal_strength,original_price,original_target,filtered_upside
0,CNC,Centene Corporation,US,NYSE,Health Care,Health Care Providers and Services,42.587276,0.090909,0.909092,10.99999,38.46,43.000,10.731348
1,PAA,Plains All American Pipeline L.P.,US,NasdaqGS,Energy,Oil Gas and Consumable Fuels,20.854547,0.090909,0.909092,10.99999,19.40,21.000,7.497664
2,UAA,Under Armour Inc.,US,NYSE,Consumer Discretionary,Textiles Apparel and Luxury Goods,5.687271,0.090909,0.909092,10.99999,7.56,5.500,-24.771547
3,AER,AerCap Holdings N.V.,IE,NYSE,Industrials,Trading Companies and Distributors,155.460923,0.090909,0.909092,10.99999,140.07,157.000,10.988022
4,ROIV,Roivant Sciences Ltd.,GB,NasdaqGS,Health Care,Biotechnology,25.983637,0.090909,0.909092,10.99999,25.82,26.000,0.633759
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4696,000060,Shenzhen Zhongjin Lingnan Nonfemet Co. Ltd.,CN,SZSE,Materials,Metals and Mining,6.006363,0.090909,0.909092,10.99999,6.87,5.920,-12.571138
4697,002895,Guizhou Chanhen Chemical Corporation,CN,SZSE,Materials,Chemicals,42.559095,0.090909,0.909092,10.99999,38.15,43.000,11.557261
4698,002402,Shenzhen H&T Intelligent Control Co.Ltd,CN,SZSE,Information Technology,Electronic Equipment Instruments and Components,44.881826,0.090909,0.909092,10.99999,36.15,45.755,24.154429
4699,002484,Nantong Jianghai Capacitor Co. Ltd.,CN,SZSE,Information Technology,Electronic Equipment Instruments and Components,35.372734,0.090909,0.909092,10.99999,28.10,36.100,25.881615
4700,300346,Jiangsu Nata Opto-electronic Material Co. Ltd.,CN,SZSE,Materials,Chemicals,52.975455,0.090909,0.909092,10.99999,52.73,53.000,0.465494

In [4]:
%%sql
# SELECT * FROM vw_features_analyst_sentiment

,isin,ticker,name,industry,sector,trading_country,region,country,exchange,analyst_bullish_pct,...,pt_median_momentum_1m,pt_median_momentum_3m,pt_acceleration_short,pt_acceleration_long,pt_consensus_convergence,analyst_coverage_change_1m,analyst_coverage_change_3m,analyst_coverage_change_1y,pt_vs_price_momentum,analyst_coverage_trend
0,US67066G1040,NVDA,NVIDIA Corporation,Semiconductors and Semiconductor Equipment,Information Technology,US,United States and Canada,US,NasdaqGS,93.650794,...,0.000000,0.111111,-0.100153,-0.356934,0.263111,1,2,4,0.116303,0.031897
1,US74006W2070,PRAX,Praxis Precision Medicines Inc.,Biotechnology,Health Care,US,United States and Canada,US,NasdaqGS,87.500000,...,0.145125,0.819820,-0.704158,-1.472271,-0.951102,1,2,6,0.064671,0.131250
2,US0378331005,AAPL,Apple Inc.,Technology Hardware Storage and Peripherals,Information Technology,US,United States and Canada,US,NasdaqGS,61.702128,...,0.000000,0.083032,-0.026305,-0.116889,-0.014019,0,0,1,0.012339,0.018293
3,US2681582019,DVAX,Dynavax Technologies Corporation,Biotechnology,Health Care,US,United States and Canada,US,NasdaqGS,33.333333,...,0.000000,0.000000,0.035088,0.084912,0.480000,0,-2,-2,-0.315846,-0.316667
4,US02079K3059,GOOGL,Alphabet Inc.,Interactive Media and Services,Communication Services,US,United States and Canada,US,NasdaqGS,89.062500,...,0.151515,0.155015,-0.056221,-0.532126,-0.118085,2,2,8,0.025202,0.040179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6415,TN0007140015,ASSAD,L'Accumulateur Tunisien Assad SA,Electrical Equipment,Industrials,TN,Africa / Middle East,TN,BVMT,0.000000,...,0.000000,0.018779,-0.018779,-2.597887,0.000000,0,0,0,-0.239099,0.000000
6416,BRTOKYACNOR5,TOKY3,Grupo Toky S.A.,Specialty Retail,Consumer Discretionary,BR,Latin America and Caribbean,BR,BOVESPA,0.000000,...,0.000000,0.000000,0.000000,0.361702,0.000000,0,0,-1,0.639344,0.000000
6417,BRTCSAACNOR3,TCSA3,Tecnisa S.A.,Household Durables,Consumer Discretionary,BR,Latin America and Caribbean,BR,BOVESPA,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,-0.219512,0.000000
6418,NGCILEASING2,CILEASING,C & I Leasing Plc,Trading Companies and Distributors,Industrials,NG,Africa / Middle East,NG,NGSE,0.000000,...,0.000000,0.000000,0.000000,NaN,0.000000,0,0,1,-0.260927,0.000000
6419,TN0006590012,SIAME,Société Industrielle d'Appareillage et de Maté...,Electrical Equipment,Industrials,TN,Africa / Middle East,TN,BVMT,100.000000,...,0.049869,0.152738,-0.102869,0.312402,0.000000,0,0,0,0.017843,0.000000

In [5]:
%%sql
# SELECT * FROM vw_features_cashflow

,isin,ticker,name,industry,sector,trading_country,region,country,exchange,cfo_to_net_income,...,fcf_ltm,fcf_fy,cfo_growth_yoy_comp,fcf_growth_yoy,cfo_to_net_income_comp,fcf_margin_comp,fcf_yield,cfo_positive_years,fcf_positive_years_comp,cash_flow_quality_score_comp
0,US0378331005,AAPL,Apple Inc.,Technology Hardware Storage and Peripherals,Information Technology,US,United States and Canada,US,NasdaqGS,1.150242,...,123324.00,98767.00,-5.726656,-9.227348,1.150242,28.310190,3.020338,5,5,100
1,US2681582019,DVAX,Dynavax Technologies Corporation,Biotechnology,Health Care,US,United States and Canada,US,NasdaqGS,-2.088249,...,80.54,60.16,-33.860382,-37.632179,-2.088249,24.368400,4.570683,4,4,25
2,US30303M1027,META,Meta Platforms Inc.,Interactive Media and Services,Communication Services,US,United States and Canada,US,NasdaqGS,1.915379,...,46109.00,46109.00,26.795725,-14.726661,1.915379,22.943682,2.755738,5,5,100
3,US1200761047,BBW,Build-A-Bear Workshop Inc.,Specialty Retail,Consumer Discretionary,US,United States and Canada,US,NYSE,1.039659,...,37.15,27.77,-26.776551,-39.656671,1.039659,7.065827,5.281565,5,5,100
4,CA05466C1095,AYA,Aya Gold & Silver Inc.,Metals and Mining,Materials,CA,United States and Canada,CA,TSX,15.663968,...,-34.72,-104.18,-355.029586,1.948235,15.663968,-25.506906,-1.459621,4,0,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6415,US8243481061,SHW,The Sherwin-Williams Company,Chemicals,Materials,US,United States and Canada,US,NYSE,0.000000,...,0.00,0.00,-100.000000,-100.000000,0.000000,0.000000,0.000000,4,4,0
6416,US4042511000,HNI,HNI Corporation,Commercial Services and Supplies,Industrials,US,United States and Canada,US,NYSE,1.764996,...,191.10,176.10,-15.252336,-7.022175,1.764996,7.369558,5.120647,5,5,100
6417,US17275R1023,CSCO,Cisco Systems Inc.,Communications Equipment,Information Technology,US,United States and Canada,US,NasdaqGS,1.330623,...,12733.00,13288.00,30.450368,30.146915,1.330623,22.069121,3.801058,5,5,100
6418,US75513E1010,RTX,RTX Corporation,Aerospace and Defense,Industrials,US,United States and Canada,US,NYSE,1.569667,...,7940.00,7940.00,47.604414,75.121306,1.569667,8.961322,2.980953,5,5,100
6419,CA96145A2002,WTE,Westshore Terminals Investment Corporation,Transportation Infrastructure,Industrials,CA,United States and Canada,CA,TSX,4.289487,...,11.01,69.34,92.529177,-6.763480,4.289487,4.200526,0.797208,5,5,100